export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

export const RESET_LOCATIONS = 'RESET_LOCATIONS';

export const LOAD_CACHED_WEATHER = 'LOAD_CACHED_WEATHER';
export const LOAD_CACHED_WEATHER_SUCCESS = 'LOAD_CACHED_WEATHER_SUCCESS';
export const LOAD_CACHED_WEATHER_FAILURE = 'LOAD_CACHED_WEATHER_FAILURE';
